### ISSUE TITLE
unsupported container flag: 3

### ISSUE THREAD

**Issue by z7ui** [HarukaMa/starfield-xgp-import#2]
========== Starfield Save File Importer ==========
WARNING: This tool is experimental. Always manually back up your existing saves!

Found container path: C:\Users\z7ui\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\000901FA30CEE012_0000000000000000000000007BF72399
Error: Detected unsupported container format, please report this issue: unsupported container flag: 3

![image](https://github.com/HarukaMa/starfield-xgp-import/assets/40062890/dc3bcf47-4c5d-4df0-ac61-452ddddb5907)

**Comment by yamatomt** [comment]
Found container path: C:\Users\uesr\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\000901F5D7281A01_0000000000000000000000007BF72399
Error: Detected unsupported container format, please report this issue: unsupported container flag: 3

**Comment by HarukaMa** [comment]
Use v0.0.2

**Comment by HarukaMa** [comment]
Please try v0.0.5 if you still have this issue.
