### ISSUE TITLE
unsupported container flag: 3

### ISSUE THREAD

**Issue by GrizzleDesign** [HarukaMa/starfield-xgp-import#5]
When trying to convert I am presented with the following error;

```
========== Starfield Save File Importer ==========
WARNING: This tool is experimental. Always manually back up your existing saves!

Found container path: C:\Users\Grizzle\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\000901FB3FE88B6C_0000000000000000000000007BF72399
Error: Detected unsupported container format, please report this issue: unsupported container flag: 3
Press any key to continue . . .
```

I have tried a few different saves as well as trying earlier verions of the converter as mentioned in a [ closed issue](https://github.com/HarukaMa/starfield-xgp-import/issues/2)

**Comment by HarukaMa** [comment]
I really should print the version number in the program output...

Try anything later than v0.0.1.

**Comment by HarukaMa** [comment]
Hmm, I think now I know what flag that was inferring to, but that is a rare bit to be on and I need to investigate it further. I'll upload a new version later to skip that detection in the meantime.

**Comment by HarukaMa** [comment]
Please try v0.0.5.

**Comment by GrizzleDesign** [comment]
Initially I had tried the latest version which was  v0.0.4

 v0.0.2, v0.0.3 and v0.0.4 were all producing the same error.

 v0.0.4 via Python did work

In regards to  v0.0.5. It has worked the two times I have tried it (via python and through the executable.)

**Comment by HarukaMa** [comment]
It seems the flag 3 (actually the second bit) indicates some transient state and will go with time, but personally I've failed to observe how that works. Maybe cloud sync related.

I'm feeling that I'd better keep this tool produced in clean room, as some internals might share with the Xbox console counterpart and trying to see more things could be dangerous for the tool.
