### ISSUE TITLE
can't sync imported steam save with the cloud

### ISSUE THREAD

**Issue by nex86** [HarukaMa/starfield-xgp-import#6]
I successfully imported my savegame from my steam game into the windows store version, but it seems its not being synced correctly with the cloud.
When I start the game on my Xbox Series S its telling me that my other device is taking longer to finish syncing than expected.
I started the game on my PC loaded up and saved again, restarted it a few times, but it doesn't seem to fully sync.

Any ideas?

**Comment by HarukaMa** [comment]
I don't own Xbox consoles, so can't really properly test that, sorry.

Maybe the `containers.index` and `container.nnn` file could help in investigating.

(The `containers.index` file contains your character name, so don't send it if you don't want to let others know that, just in case)

**Comment by nex86** [comment]
Nevermind! it works now! just had to wait a bit longer. seems the servers are a tad slow..?

**Comment by HarukaMa** [comment]
Maybe the Xbox app doesn't like unexpected changes to the file, but yes sometimes the syncing takes longer than a few seconds and you can't even know if it's still syncing.

Glad it worked out in the end.
